#!/usr/bin/perl -w

use strict;
use utf8;
use open ':std', ':encoding(UTF-8)';
use FindBin qw($Bin $RealBin $Script);
use Getopt::Long::Descriptive;
use Math::Trig;

sub getTileNumber {
    my ($lat,$lon,$zoom) = @_;
    my $xtile = int( ($lon+180)/360 * 2**$zoom ) ;
    my $ytile = int( (1 - log(tan(deg2rad($lat)) + sec(deg2rad($lat)))/pi)/2 * 2**$zoom ) ;
    return ($xtile, $ytile);
}


my ($opt, $usage) = describe_options(
        "$Script %o <some-arg>",
        [ 'zoom|z=s',		"Zoom level", { required => 1 } ],
        [ 'uribase|u=s',	"Zoom level", { required => 1 } ],
        [ 'left|l=s',		"Left longitude", { required => 1 } ],
        [ 'right|r=s',		"Right longitude", { required => 1 } ],
        [ 'top|t=s',		"Top latitude", { required => 1 } ],
        [ 'bottom|b=s',		"Bottom latitude", { required => 1 } ],
        [],
        [ 'help',               "print usage message and exit", { shortcircuit => 1 } ],
);

print($usage->text), exit if $opt->help;

my ($left, $bottom)=getTileNumber($opt->bottom*1, $opt->left*1, $opt->zoom);
my ($right, $top)=getTileNumber($opt->top*1, $opt->right*1, $opt->zoom);

printf(STDERR "Left: $left Right: $right\n");
printf(STDERR "Top: $top Bottom: $bottom\n");

# http://a.tile.zz.de/tile/12/2145/1353.png
for(my $x=$left;$x<=$right;$x++) {
	for(my $y=$top;$y<=$bottom;$y++) {
		printf("%s/%s/%s/%s.png\n",
			$opt->uribase,
			$opt->zoom, $x, $y);
	}
}


