#!/bin/bash

DATADIR="/current/$1"

SU="sudo -u renderer"
PSQL="${SU} psql gis "


boundary_import() {
	BOUNDARYGZ=$(ls -1 ${DATADIR}/*.geojson.gz)
	zcat ${BOUNDARYGZ} >/tmp/boundary.geojson

	${SU} ogr2ogr -f "PostgreSQL" PG:"dbname=gis" \
		"/tmp/boundary.geojson" \
		-nln boundaries -overwrite \
		-t_srs "EPSG:3857"
}

simplified_water_import() {
	#/home/renderer/src/openstreetmap-carto/data/simplified-water-polygons-split-3857/simplified_water_polygons.shp
	#/home/renderer/src/openstreetmap-carto/data/water-polygons-split-3857/water_polygons.shp
	#/home/renderer/src/openstreetmap-carto/data/antarctica-icesheet-outlines-3857/icesheet_outlines.shp
	#/home/renderer/src/openstreetmap-carto/data/ne_110m_admin_0_boundary_lines_land/ne_110m_admin_0_boundary_lines_land.shp
	#/home/renderer/src/openstreetmap-carto/data/antarctica-icesheet-polygons-3857/icesheet_polygons.shp

	${SU} ogr2ogr -f "PostgreSQL" PG:"dbname=gis" \
		-nln water_polygons -overwrite -t_srs "EPSG:3857" \
		/home/renderer/src/openstreetmap-carto/data/water-polygons-split-3857/water_polygons.shp
}

gdal_update() {

	dpkg --compare-versions $(dpkg-query -f '${Version}' -W gdal-bin) gt 3
	if [ $? -eq 0 ]; then
		return
	fi

	# Bionic gdal 2.2.3 is broken using Postgres 12
	# so we need temporarily for the import of the geojson
	# a gdal 3.0.2+ - Install from ubuntugis-unstable

	apt-get update
	apt-get -fuy install software-properties-common
	add-apt-repository ppa:ubuntugis/ubuntugis-unstable
	apt-get update
	apt-get -fuy install gdal-bin
}

set -x

gdal_update
boundary_import
simplified_water_import

${PSQL} --echo-all -f "/current/processboundary.sql"
${PSQL} --echo-all -f "/current/droptables.sql"

sync
sleep 1
/etc/init.d/postgresql stop
sync
sleep 1
sync
